import { portfolioSchema } from './portfolio.schema'
import { portfolioProfile } from './profile.data'

const portfolioCandidate = {
  profile: portfolioProfile,
  skills: [
    { id: 'typescript', label: { fr: 'TypeScript', en: 'TypeScript' }, category: 'language' },
    { id: 'python', label: { fr: 'Python', en: 'Python' }, category: 'language' },
    { id: 'php', label: { fr: 'PHP', en: 'PHP' }, category: 'language' },
    { id: 'csharp', label: { fr: 'C#', en: 'C#' }, category: 'language' },
    { id: 'c', label: { fr: 'C', en: 'C' }, category: 'language' },
    { id: 'cpp', label: { fr: 'C++', en: 'C++' }, category: 'language' },
    { id: 'java', label: { fr: 'Java', en: 'Java' }, category: 'language' },
    { id: 'javascript', label: { fr: 'JavaScript', en: 'JavaScript' }, category: 'language' },
    { id: 'sql', label: { fr: 'SQL', en: 'SQL' }, category: 'language' },
    { id: 'bash', label: { fr: 'Bash', en: 'Bash' }, category: 'language' },
    { id: 'kotlin', label: { fr: 'Kotlin', en: 'Kotlin' }, category: 'language' },
    { id: 'dart', label: { fr: 'Dart', en: 'Dart' }, category: 'language' },
    { id: 'xaml', label: { fr: 'XAML', en: 'XAML' }, category: 'language' },
    { id: 'html-css', label: { fr: 'HTML / CSS', en: 'HTML / CSS' }, category: 'language' },
    { id: 'react', label: { fr: 'React', en: 'React' }, category: 'framework' },
    { id: 'angular', label: { fr: 'Angular', en: 'Angular' }, category: 'framework' },
    { id: 'vite', label: { fr: 'Vite', en: 'Vite' }, category: 'framework' },
    { id: 'flutter', label: { fr: 'Flutter', en: 'Flutter' }, category: 'framework' },
    { id: 'unity', label: { fr: 'Unity', en: 'Unity' }, category: 'framework' },
    { id: 'spring-boot', label: { fr: 'Spring Boot', en: 'Spring Boot' }, category: 'framework' },
    { id: 'tailwind', label: { fr: 'Tailwind', en: 'Tailwind' }, category: 'framework' },
    { id: 'mapping', label: { fr: 'Cartographie logicielle', en: 'Software mapping' }, category: 'domain' },
    { id: 'testing', label: { fr: 'Tests end-to-end', en: 'End-to-end testing' }, category: 'domain' },
    { id: 'architecture', label: { fr: 'Architecture PWA', en: 'PWA architecture' }, category: 'domain' },
    { id: 'cybersecurity', label: { fr: 'Cybersécurité web', en: 'Web cybersecurity' }, category: 'domain' },
    { id: 'devops', label: { fr: 'DevOps', en: 'DevOps' }, category: 'domain' },
    { id: 'project-management', label: { fr: 'Gestion de projet', en: 'Project management' }, category: 'domain' },
    { id: 'generative-ai', label: { fr: 'IA générative appliquée', en: 'Applied generative AI' }, category: 'domain' },
    { id: 'offensive-security', label: { fr: 'Sécurité offensive', en: 'Offensive security' }, category: 'domain' },
    { id: 'physical-pentesting', label: { fr: 'Pentest physique', en: 'Physical pentesting' }, category: 'domain' },
    { id: 'access-control', label: { fr: "Sécurité du contrôle d'accès", en: 'Access-control security' }, category: 'domain' },
    { id: 'nfc-rfid', label: { fr: 'NFC / RFID', en: 'NFC / RFID' }, category: 'domain' },
    { id: 'biometrics', label: { fr: 'Biométrie', en: 'Biometrics' }, category: 'domain' },
    { id: 'radio-frequency', label: { fr: 'Radiofréquence / sub-GHz', en: 'Radio frequency / sub-GHz' }, category: 'domain' },
    { id: 'infrared', label: { fr: 'Infrarouge', en: 'Infrared' }, category: 'domain' },
    { id: 'hardware-prototyping', label: { fr: 'Prototypage matériel', en: 'Hardware prototyping' }, category: 'domain' },
    { id: 'red-team', label: { fr: 'Reconnaissance Red Team', en: 'Red Team reconnaissance' }, category: 'domain' },
    { id: 'codex', label: { fr: 'Codex', en: 'Codex' }, category: 'tool' },
    { id: 'claude', label: { fr: 'Claude', en: 'Claude' }, category: 'tool' },
    { id: 'git', label: { fr: 'Git / GitHub', en: 'Git / GitHub' }, category: 'tool' },
    { id: 'mysql', label: { fr: 'MySQL', en: 'MySQL' }, category: 'tool' },
    { id: 'android-studio', label: { fr: 'Android Studio', en: 'Android Studio' }, category: 'tool' },
    { id: 'jira', label: { fr: 'Jira', en: 'Jira' }, category: 'tool' },
    { id: 'catia', label: { fr: 'Catia', en: 'Catia' }, category: 'tool' },
    { id: 'docker', label: { fr: 'Docker', en: 'Docker' }, category: 'tool' },
    { id: 'linux', label: { fr: 'Linux', en: 'Linux' }, category: 'tool' },
    { id: 'office-365', label: { fr: 'Suite Office 365', en: 'Office 365 suite' }, category: 'tool' },
    { id: 'cc1101', label: { fr: 'CC1101', en: 'CC1101' }, category: 'tool' },
    { id: 'esp32', label: { fr: 'ESP32-S3 / C5', en: 'ESP32-S3 / C5' }, category: 'tool' },
    { id: 'usb', label: { fr: 'Périphériques USB', en: 'USB devices' }, category: 'tool' },
  ],
  languages: [
    { id: 'french', label: { fr: 'Français', en: 'French' }, level: { fr: 'Natif', en: 'Native' } },
    { id: 'english', label: { fr: 'Anglais', en: 'English' }, level: { fr: 'Courant', en: 'Fluent' } },
    { id: 'mandarin', label: { fr: 'Mandarin', en: 'Mandarin' }, level: { fr: 'Courant', en: 'Fluent' } },
    { id: 'spanish', label: { fr: 'Espagnol', en: 'Spanish' }, level: { fr: 'Néophyte', en: 'Beginner' } },
  ],
  softSkills: [
    { id: 'teamwork', label: { fr: 'Travail d’équipe', en: 'Teamwork' } },
    { id: 'versatility', label: { fr: 'Polyvalence', en: 'Versatility' } },
    { id: 'communication', label: { fr: 'Communication', en: 'Communication' } },
    { id: 'analysis', label: { fr: 'Esprit d’analyse', en: 'Analytical thinking' } },
    { id: 'problem-solving', label: { fr: 'Résolution de problèmes', en: 'Problem solving' } },
    { id: 'agile', label: { fr: 'Méthode agile', en: 'Agile methodology' } },
    { id: 'creativity', label: { fr: 'Créativité', en: 'Creativity' } },
    { id: 'rigor', label: { fr: 'Rigueur', en: 'Rigor' } },
    { id: 'autonomy', label: { fr: 'Autonomie', en: 'Autonomy' } },
    { id: 'curiosity', label: { fr: 'Curiosité', en: 'Curiosity' } },
    { id: 'perseverance', label: { fr: 'Persévérance', en: 'Perseverance' } },
    { id: 'adaptability', label: { fr: "Capacité d'adaptation", en: 'Adaptability' } },
    { id: 'organization', label: { fr: 'Organisation', en: 'Organization' } },
    { id: 'initiative', label: { fr: "Prise d'initiative", en: 'Initiative' } },
    { id: 'listening', label: { fr: 'Écoute', en: 'Attentiveness' } },
    { id: 'feedback', label: { fr: "Transformation des retours en axes d'amélioration", en: 'Turning feedback into concrete improvements' } },
    { id: 'engineering-mindset', label: { fr: 'Esprit ingénieur', en: 'Engineering mindset' } },
  ],
  experiences: [
    {
      id: 'thales',
      company: 'Thales',
      role: { fr: 'Software Engineer en alternance', en: 'Software Engineer Apprentice' },
      period: { fr: '2023–2026 · 3 ans', en: '2023–2026 · 3 years' },
      summary: {
        fr: "Trois ans consacrés au développement et à la maintenance de TIMS.JS, un SDK cartographique TypeScript mutualisé utilisé par plus de 100 développeurs au sein de Thales et de plusieurs programmes partenaires.",
        en: 'Three years developing and maintaining TIMS.JS, a shared TypeScript mapping SDK used by more than 100 developers across Thales and several partner programs.',
      },
      missions: [
        {
          fr: "Conception et intégration de nouvelles capacités conformes aux standards NVG Binding, MIL-STD-2525 et APP-6E pour assurer l'interopérabilité et répondre aux nouveaux besoins opérationnels.",
          en: 'Designed and integrated new capabilities compliant with NVG Binding, MIL-STD-2525, and APP-6E to ensure interoperability and address emerging operational requirements.',
        },
        {
          fr: 'Pilotage du chantier APP-6E : analyse d’impact, estimation, priorisation et coordination des releases.',
          en: 'Led the APP-6E workstream: impact analysis, estimation, prioritization, and release coordination.',
        },
        {
          fr: 'Automatisation de tests end-to-end pour sécuriser les évolutions et détecter les régressions.',
          en: 'Automated end-to-end tests to secure changes and detect regressions.',
        },
        {
          fr: "Réalisation de l'étude préliminaire et proposition de l'architecture d'Atlas Lite, version mobile du système de commandement d'artillerie ATLAS, avec une approche PWA adaptée aux contraintes opérationnelles et d'évolutivité.",
          en: 'Conducted the preliminary study and proposed the architecture for Atlas Lite, a mobile version of the ATLAS artillery command system, using a PWA approach aligned with operational and scalability constraints.',
        },
        {
          fr: "Utilisation raisonnée de l'IA générative pour accélérer le prototypage, le développement, la génération de tests, l'analyse technique et la documentation, avec validation systématique des résultats.",
          en: 'Used generative AI responsibly to accelerate prototyping, development, test generation, technical analysis, and documentation, with systematic validation of outputs.',
        },
      ],
      skillIds: ['typescript', 'mapping', 'testing', 'architecture', 'generative-ai'],
      publicationApproved: true,
    },
    {
      id: 'ekino-vietnam',
      company: 'Ekino - Vietnam',
      role: { fr: 'Stagiaire ingénieur cybersécurité', en: 'Cybersecurity Engineer Intern' },
      period: { fr: 'Juin–juillet 2026 · 2 mois', en: 'June–July 2026 · 2 months' },
      summary: {
        fr: "Analyse de la sécurité d'applications web et automatisation de la détection de vulnérabilités.",
        en: 'Web application security analysis and automation of vulnerability detection.',
      },
      missions: [
        {
          fr: 'Identification de vulnérabilités telles que les XSS et injections SQL.',
          en: 'Identified vulnerabilities including XSS and SQL injection.',
        },
        {
          fr: 'Développement de scripts d’automatisation pour accélérer la détection et la vérification.',
          en: 'Developed automation scripts to accelerate vulnerability detection and verification.',
        },
        {
          fr: "Utilisation raisonnée d'outils d'IA générative pour générer et améliorer des scripts, explorer des pistes techniques et soutenir l'analyse, avec vérification systématique des réponses.",
          en: 'Used generative AI tools responsibly to generate and improve scripts, explore technical approaches, and support analysis, with systematic verification of outputs.',
        },
        {
          fr: 'Analyse des résultats et proposition de pistes de correction, avec contributions DevOps ponctuelles.',
          en: 'Analyzed results and proposed remediation approaches, with occasional DevOps contributions.',
        },
      ],
      skillIds: ['cybersecurity', 'offensive-security', 'python', 'devops', 'generative-ai'],
      publicationApproved: true,
    },
    {
      id: 'agence3d',
      company: "L'Agence3D",
      role: { fr: 'Développeur', en: 'Developer' },
      period: { fr: 'Février–juillet 2023 · 6 mois', en: 'February–July 2023 · 6 months' },
      summary: {
        fr: 'Développement d’une PWA et contribution à plusieurs projets web, de la conception à la mise en production.',
        en: 'Developed a PWA and contributed to several web projects, from design through production deployment.',
      },
      missions: [
        {
          fr: 'Conception et suivi de fonctionnalités full-stack avec React et PHP.',
          en: 'Designed and oversaw full-stack features using React and PHP.',
        },
        {
          fr: 'Collaboration avec les équipes créatives pour assurer la cohérence technique et visuelle.',
          en: 'Worked with creative teams to ensure technical and visual consistency.',
        },
      ],
      skillIds: ['react', 'php', 'architecture'],
      publicationApproved: true,
    },
    {
      id: 'region-idf',
      company: 'Région Île-de-France',
      role: { fr: 'Chef de projet et développeur', en: 'Project Manager and Developer' },
      period: { fr: 'Juillet–décembre 2022 · 6 mois', en: 'July–December 2022 · 6 months' },
      summary: {
        fr: 'Développement d’une application mobile pour la promotion de la région Île-de-France.',
        en: 'Developed a mobile application promoting the Île-de-France region.',
      },
      missions: [
        {
          fr: 'Suivi des objectifs et du planning du projet.',
          en: 'Tracked project objectives and schedules.',
        },
        {
          fr: 'Conception d’interfaces et développement full-stack avec React, Flutter, PHP, C#, Java et MySQL.',
          en: 'Designed interfaces and delivered full-stack work using React, Flutter, PHP, C#, Java, and MySQL.',
        },
      ],
      skillIds: ['project-management', 'react', 'flutter', 'html-css', 'php', 'csharp', 'java', 'mysql'],
      publicationApproved: true,
    },
    {
      id: 'sleepless',
      company: 'Sleepless',
      role: { fr: 'Chef de projet et développeur', en: 'Project Manager and Developer' },
      period: { fr: 'Janvier–juin 2022 · 6 mois', en: 'January–June 2022 · 6 months' },
      summary: {
        fr: 'Gestion de projet, conception d’interfaces et développement full-stack.',
        en: 'Project management, interface design, and full-stack development.',
      },
      missions: [
        {
          fr: 'Suivi des objectifs et du planning.',
          en: 'Tracked objectives and schedules.',
        },
        {
          fr: 'Travail avec React, Flutter, HTML/CSS, PHP, C#, Java et MySQL.',
          en: 'Worked with React, Flutter, HTML/CSS, PHP, C#, Java, and MySQL.',
        },
      ],
      skillIds: ['project-management', 'react', 'flutter', 'html-css', 'php', 'csharp', 'java', 'mysql'],
      publicationApproved: true,
    },
    {
      id: 'ecp',
      company: "Europ' Computer Performance",
      role: { fr: 'Développeur', en: 'Developer' },
      period: { fr: 'Mai–août 2021 · 4 mois', en: 'May–August 2021 · 4 months' },
      summary: {
        fr: 'Maintenance et optimisation du site web de l’entreprise pour améliorer performances et expérience utilisateur.',
        en: 'Maintained and optimized the company website to improve performance and user experience.',
      },
      missions: [
        {
          fr: 'Diagnostic et correction d’anomalies techniques.',
          en: 'Diagnosed and fixed technical issues.',
        },
        {
          fr: 'Développement de nouvelles fonctionnalités répondant aux besoins métiers.',
          en: 'Developed new features to meet business needs.',
        },
      ],
      skillIds: ['javascript', 'php', 'sql'],
      publicationApproved: true,
    },
  ],
  education: [
    {
      id: 'epita',
      institution: 'EPITA',
      program: {
        fr: "École d'ingénieurs en informatique",
        en: 'Graduate School of Computer Science',
      },
      highlights: [
        { fr: 'Jeu vidéo en C# développé pendant six mois.', en: 'Developed a C# video game over six months.' },
        { fr: 'Launcher de jeux vidéo en XAML.', en: 'Developed a video game launcher in XAML.' },
        { fr: 'Logiciel de reconnaissance de caractères en C.', en: 'Developed optical character recognition software in C.' },
        { fr: 'Shell conforme POSIX en C (42SH).', en: 'Developed a POSIX-compliant shell in C (42SH).' },
        { fr: 'Projets intensifs en C, C++, SQL, Java et JavaScript.', en: 'Intensive projects in C, C++, SQL, Java, and JavaScript.' },
      ],
      skillIds: ['c', 'cpp', 'csharp', 'java', 'javascript', 'sql', 'xaml'],
      publicationApproved: true,
    },
    {
      id: 'heriot-watt',
      institution: 'Heriot-Watt University',
      program: { fr: 'Semestre international', en: 'International semester' },
      highlights: [
        { fr: 'Ambassadeur étudiant de l’EPITA en Écosse.', en: 'EPITA student ambassador in Scotland.' },
        { fr: 'Création d’un site dynamique en HTML, CSS et PHP.', en: 'Built a dynamic website using HTML, CSS, and PHP.' },
        { fr: 'Développement d’une application en Flutter.', en: 'Developed an application in Flutter.' },
      ],
      skillIds: ['html-css', 'php', 'flutter', 'dart', 'javascript'],
      publicationApproved: true,
    },
    {
      id: 'francs-bourgeois',
      institution: 'Lycée des Francs-Bourgeois',
      program: {
        fr: 'Baccalauréat scientifique avec mention',
        en: 'French Scientific Baccalaureate with honors',
      },
      highlights: [
        { fr: 'Formation scientifique générale.', en: 'General scientific education.' },
      ],
      skillIds: [],
      publicationApproved: true,
    },
  ],
  projects: [
    {
      id: 'csharp-game',
      title: { fr: 'Jeu vidéo en C#', en: 'C# video game' },
      context: { fr: 'EPITA · projet de six mois', en: 'EPITA · six-month project' },
      summary: { fr: 'Programmation d’un jeu vidéo en C#.', en: 'Development of a video game in C#.' },
      details: [
        { fr: 'Projet académique développé sur une période de six mois.', en: 'Academic project developed over a six-month period.' },
      ],
      skillIds: ['csharp'],
      publicationApproved: true,
    },
    {
      id: 'xaml-launcher',
      title: { fr: 'Launcher de jeux vidéo', en: 'Video game launcher' },
      context: { fr: 'EPITA · projet académique', en: 'EPITA · academic project' },
      summary: { fr: 'Programmation d’un launcher de jeux vidéo en XAML.', en: 'Development of a video game launcher in XAML.' },
      details: [
        { fr: 'Interface réalisée en XAML avec une logique applicative en C#.', en: 'Interface built in XAML with application logic in C#.' },
      ],
      skillIds: ['xaml', 'csharp'],
      publicationApproved: true,
    },
    {
      id: 'ocr',
      title: { fr: 'Reconnaissance de caractères', en: 'Optical character recognition' },
      context: { fr: 'EPITA · projet académique', en: 'EPITA · academic project' },
      summary: { fr: 'Programmation d’un logiciel OCR en C.', en: 'Development of OCR software in C.' },
      details: [
        { fr: 'Projet consacré à la reconnaissance optique de caractères.', en: 'Project focused on optical character recognition.' },
      ],
      skillIds: ['c'],
      publicationApproved: true,
    },
    {
      id: '42sh',
      title: { fr: 'Shell POSIX 42SH', en: '42SH POSIX shell' },
      context: { fr: 'EPITA · projet académique', en: 'EPITA · academic project' },
      summary: { fr: 'Programmation d’un shell conforme POSIX en C.', en: 'Development of a POSIX-compliant shell in C.' },
      details: [
        { fr: 'Implémentation en C avec pour objectif la conformité POSIX.', en: 'Implemented in C with POSIX compliance as a core requirement.' },
      ],
      skillIds: ['c'],
      publicationApproved: true,
    },
    {
      id: 'heriot-web',
      title: { fr: 'Site web dynamique', en: 'Dynamic website' },
      context: { fr: 'Heriot-Watt · semestre international', en: 'Heriot-Watt · international semester' },
      summary: { fr: 'Création d’un site dynamique en HTML, CSS et PHP.', en: 'Built a dynamic website using HTML, CSS, and PHP.' },
      details: [
        { fr: 'Projet réalisé pendant un semestre international en Écosse.', en: 'Project completed during an international semester in Scotland.' },
      ],
      skillIds: ['html-css', 'php', 'javascript'],
      publicationApproved: true,
    },
    {
      id: 'heriot-flutter',
      title: { fr: 'Application Flutter', en: 'Flutter application' },
      context: { fr: 'Heriot-Watt · semestre international', en: 'Heriot-Watt · international semester' },
      summary: { fr: 'Programmation d’une application en Flutter.', en: 'Development of an application in Flutter.' },
      details: [
        { fr: 'Application mobile développée avec Flutter et Dart.', en: 'Mobile application developed with Flutter and Dart.' },
      ],
      skillIds: ['flutter', 'dart'],
      publicationApproved: true,
    },
    {
      id: 'physical-pentesting-lab',
      title: { fr: 'Laboratoire de pentest physique', en: 'Physical pentesting lab' },
      context: { fr: 'Projet cyber personnel · Red Team', en: 'Personal cybersecurity project · Red Team' },
      summary: {
        fr: "Exploration pratique des mécanismes de contrôle d'accès physique et de leurs limites.",
        en: 'Hands-on exploration of physical access-control mechanisms and their limitations.',
      },
      details: [
        { fr: 'Crochetage de serrures et étude des mécanismes physiques.', en: 'Lock picking and study of physical locking mechanisms.' },
        { fr: 'Expérimentation autour des badges NFC/RFID.', en: 'Experiments involving NFC/RFID badges.' },
        { fr: "Étude de la biométrie et des systèmes de contrôle d'accès.", en: 'Study of biometrics and access-control systems.' },
      ],
      skillIds: ['physical-pentesting', 'nfc-rfid', 'biometrics', 'access-control'],
      publicationApproved: true,
    },
    {
      id: 'rf-infrared-lab',
      title: { fr: 'Laboratoire radiofréquence et infrarouge', en: 'Radio-frequency and infrared lab' },
      context: { fr: 'Projet cyber personnel · systèmes embarqués', en: 'Personal cybersecurity project · embedded systems' },
      summary: {
        fr: 'Expérimentation sur les communications sub-GHz et infrarouges avec des composants dédiés.',
        en: 'Experimentation with sub-GHz and infrared communications using dedicated components.',
      },
      details: [
        { fr: 'Travail sur les communications sub-GHz avec des modules CC1101.', en: 'Work on sub-GHz communications using CC1101 modules.' },
        { fr: 'Exploration de plateformes ESP32-S3 et ESP32-C5.', en: 'Exploration of ESP32-S3 and ESP32-C5 platforms.' },
        { fr: 'Expérimentations autour des signaux infrarouges.', en: 'Experiments involving infrared signals.' },
      ],
      skillIds: ['radio-frequency', 'infrared', 'cc1101', 'esp32'],
      publicationApproved: true,
    },
    {
      id: 'hardware-prototyping-lab',
      title: { fr: 'Prototypage matériel pour la cybersécurité', en: 'Cybersecurity hardware prototyping' },
      context: { fr: 'Projet cyber personnel · prototypage', en: 'Personal cybersecurity project · prototyping' },
      summary: {
        fr: 'Assemblage et expérimentation avec des plateformes compactes et des périphériques matériels.',
        en: 'Assembly and experimentation with compact platforms and hardware peripherals.',
      },
      details: [
        { fr: 'Utilisation du T-Embed CC1101 Plus.', en: 'Use of the T-Embed CC1101 Plus.' },
        { fr: 'Utilisation de T-Dongle S3/C5.', en: 'Use of T-Dongle S3/C5 devices.' },
        { fr: 'Prototypage avec des périphériques USB.', en: 'Prototyping with USB devices.' },
      ],
      skillIds: ['hardware-prototyping', 'cc1101', 'esp32', 'usb'],
      publicationApproved: true,
    },
    {
      id: 'red-team-recon',
      title: { fr: 'Reconnaissance et contournement d’accès', en: 'Reconnaissance and access bypass' },
      context: { fr: 'Projet cyber personnel · Red Team', en: 'Personal cybersecurity project · Red Team' },
      summary: {
        fr: "Travail personnel autour des méthodes de reconnaissance et du contournement des contrôles d'accès.",
        en: 'Personal work involving reconnaissance methods and access-control bypass.',
      },
      details: [
        { fr: 'Étude de démarches de reconnaissance Red Team.', en: 'Study of Red Team reconnaissance approaches.' },
        { fr: "Exploration des limites et contournements des mécanismes d'accès.", en: 'Exploration of access mechanism limitations and bypasses.' },
      ],
      skillIds: ['red-team', 'offensive-security', 'access-control'],
      publicationApproved: true,
    },
  ],
  interests: [
    { id: 'climbing', label: { fr: 'Escalade', en: 'Climbing' }, description: { fr: "Une galerie de mes sorties et séances d'escalade.", en: 'A gallery of my climbing outings and sessions.' }, mediaFolder: 'climbing', publicationApproved: true },
    { id: 'leathercraft', label: { fr: 'Maroquinerie', en: 'Leathercraft' }, description: { fr: 'Pièces en cuir, essais et étapes de fabrication.', en: 'Leather pieces, experiments, and making process.' }, mediaFolder: 'leathercraft', publicationApproved: true },
    { id: 'jewelry', label: { fr: 'Joaillerie', en: 'Jewelry' }, description: { fr: 'Créations et travaux personnels de joaillerie.', en: 'Personal jewelry creations and work.' }, mediaFolder: 'jewelry', publicationApproved: true },
    { id: 'woodworking', label: { fr: 'Menuiserie', en: 'Woodworking' }, description: { fr: 'Projets personnels de fabrication et de travail du bois.', en: 'Personal making and woodworking projects.' }, mediaFolder: 'woodworking', publicationApproved: true },
    { id: 'lockpicking', label: { fr: 'Crochetage de serrures', en: 'Lock picking' }, description: { fr: 'Pratique intégrée à mon laboratoire personnel de pentest physique.', en: 'Practice forming part of my personal physical-pentesting lab.' }, mediaFolder: 'lockpicking', publicationApproved: true },
    { id: 'swimming', label: { fr: 'Natation', en: 'Swimming' }, description: { fr: 'Galerie consacrée à ma pratique de la natation.', en: 'A gallery dedicated to my swimming practice.' }, mediaFolder: 'swimming', publicationApproved: true },
    { id: 'traveling', label: { fr: 'Voyages', en: 'Travel' }, description: { fr: 'Souvenirs visuels de mes voyages et découvertes.', en: 'Visual memories from my travels and discoveries.' }, mediaFolder: 'traveling', publicationApproved: true },
  ],
  links: [
    {
      kind: 'phone',
      label: { fr: 'Téléphone', en: 'Phone' },
      href: 'tel:+33695523317',
    },
    {
      kind: 'email',
      label: { fr: 'E-mail', en: 'Email' },
      href: 'mailto:willy.somkhit@epita.fr',
    },
    {
      kind: 'github',
      label: { fr: 'GitHub', en: 'GitHub' },
      href: 'https://github.com/Xyphes',
    },
    {
      kind: 'linkedin',
      label: { fr: 'LinkedIn', en: 'LinkedIn' },
      href: 'https://www.linkedin.com/in/willy-somkhit/',
    },
  ],
  documents: [
    {
      id: 'cv',
      label: { fr: 'Télécharger mon CV', en: 'Download my resume' },
      href: '/documents/CV-Somkhit-Willy-2026-FR-ENG.pdf',
      preview: {
        fr: '/documents/CV-preview-fr.png',
        en: '/documents/CV-preview-en.png',
      },
    },
    {
      id: 'recommendation',
      label: { fr: 'Lettre de recommandation', en: 'Recommendation letter' },
      href: '/documents/Lettre-recommandation-Julien-Mullet-FR-EN.pdf',
    },
  ],
} as const

export const portfolio = portfolioSchema.parse(portfolioCandidate)
